version: '3.8'
services:
    db:
        build: 
            context: ./DB
            dockerfile: ./Dockerfile
        image: 'postgresdb:1'        
        env_file: 'env.env'
        environment: 
            - POSTGRES_PASSWORD=password
        ports: 
            - 5432:5432
    transfer:
        build:
            context: ./Transfer
            dockerfile: Dockerfile
        image: 'transfer:1'
        env_file: 'env.env'
        environment: 
            - LOG_LEVEL=DEBUG
        ports:
            - 8081:8081            
        depends_on:
            - db        
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8081/heartbeat"]
            interval: 1m
            timeout: 10s
            retries: 3
            start_period: 10s  

    
    #ui:
    #    build:
    #        context: ./WebUI
    #        dockerfile: Dockerfile
    #    image: 'detectorui:1'
    #    env_file: 'minidetector.env'
    #    environment:
    #        - DB_SERVER=db            
    #    depends_on:
    #        - db
    #    ports: 
    #        - 80:8080
    #    command: "--debug"