version: '3.8'
services:
    db:
        build: 
            context: ./DB
            dockerfile: ./Dockerfile
        image: 'postgresdb:1'        
        env_file: 'env.env'
        environment: 
            - POSTGRES_PASSWORD=password
        ports: 
            - 5432:5432
    transfer:
        build:
            context: ./Transfer
            dockerfile: Dockerfile
        image: 'transfer:1'
        env_file: 'env.env'
        environment: 
            - LOG_LEVEL=INFO
        ports:
            - 8081:8081            
        depends_on:
            - db        
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8081/heartbeat"]
            interval: 1m
            timeout: 10s
            retries: 3
            start_period: 10s  

    loader:
        build:
            context: ./Loader
            dockerfile: Dockerfile
        image: 'loader:1'        
        environment:
            - SERVER_URL=http://transfer:8081/sendfiles
            - LOG_LEVEL=INFO        
        depends_on:
            - transfer        

